openapi: 3.0.0
info:
  title: Sample API
  version: 0.1.9

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /home:
    get:
      summary: Returns a list of homepage sections.
      responses:
        '200': # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    heading:
                      type: string
                    f:
                      type: array
                      items:
                        oneOf:
                          - $ref: '#/components/schemas/RFCCard'
                          - $ref: '#/components/schemas/Card'
                        discriminator:
                          propertyName: cardType

components:
  schemas:
    RFCCard:
      type: object
      properties:
        cardType:
          type: string
          enum: ['RFCCard']
        id:
          type: string
        classification:
          type: string
        abstract:
          type: string

    Card:
      type: object
      properties:
        cardType:
          type: string
          enum: ['Card']
        href:
          type: string
        title:
          type: string
        body:
          type: integer
