// Generated file by generate-markdown-links.ts DO NOT EDIT
export type MarkdownValidHrefs =
  | "/about/contact/"
  | "/about/contact/#contact"
  | "/about/contact/#report-a-copyright-infringement"
  | "/about/rfc-editor/"
  | "/about/rfc-editor/#about-the-rfc-editor"
  | "/about/rfc-editor/#rswg"
  | "/about/rfc-editor/#rsab"
  | "/about/rfc-editor/#rsce"
  | "/about/rfc-editor/#rpc"
  | "/about/rfc-editor/#governing-rfcs"
  | "/about/rpc-reports/"
  | "/about/rpc-reports/#reports"
  | "/about/rpc-reports/#service-level-agreement"
  | "/about/rpc-reports/#notes"
  | "/about/rpc-reports/#other-reports"
  | "/series/rfc-download/"
  | "/series/rfc-download/#download-rfcs"
  | "/series/rfc-download/#feed-of-recently-published-rfcs"
  | "/series/rfc-download/#download-rfcs-using-rsync"
  | "/series/rfc-download/#to-get-the-list-of-modules-available-type-rsync-rsyncrfc-editororg-this-will-return-the-following-results"
  | "/series/rfc-download/#to-create-a-mirror-using-a-module"
  | "/series/rfc-download/#download-rfcs-in-tar-or-zip-files"
  | "/series/rfc-errata/"
  | "/series/rfc-errata/#errata-in-rfcs"
  | "/series/rfc-errata/#types-of-errata"
  | "/series/rfc-errata/#errata-statuses"
  | "/series/rfc-errata/#how-to-report-an-erratum"
  | "/series/rfc-errata/#search-for-errata"
  | "/series/rfc-faq/"
  | "/series/rfc-faq/#frequently-asked-questions"
  | "/series/rfc-faq/#who"
  | "/series/rfc-faq/#wg"
  | "/series/rfc-faq/#allstds"
  | "/series/rfc-faq/#stdtrack"
  | "/series/rfc-faq/#statuschanges"
  | "/series/rfc-faq/#errata"
  | "/series/rfc-faq/#copyright"
  | "/series/rfc-faq/#streamcat"
  | "/series/rfc-faq/#streamman"
  | "/series/rfc-faq/#notified"
  | "/series/rfc-faq/#retrieve"
  | "/series/rfc-faq/#controlM"
  | "/series/rfc-faq/#hardcopy"
  | "/series/rfc-faq/#how"
  | "/series/rfc-faq/#in-queue"
  | "/series/rfc-faq/#howlong"
  | "/series/rfc-faq/#reservednumber"
  | "/series/rfc-faq/#expedite"
  | "/series/rfc-faq/#typos"
  | "/series/rfc-faq/#style"
  | "/series/rfc-faq/#refs"
  | "/series/rfc-faq/#IDrefs"
  | "/series/rfc-faq/#lastlook"
  | "/series/rfc-faq/#missingauthor"
  | "/series/rfc-faq/#involved"
  | "/series/rfc-faq/#enhanced"
  | "/series/rfc-faq/#sourcefile"
  | "/series/rfc-faq/#notprepped"
  | "/series/rfc-faq/#april"
  | "/series/rfc-faq/#process"
  | "/series/rfc-faq/#xmlfile"
  | "/series/rfc-faq/#a404xml"
  | "/series/rfc-faq/#whichsource"
  | "/series/rfc-faq/#changes"
  | "/series/rfc-faq/#pagebreaks"
  | "/series/rfc-faq/#approval"
  | "/series/rfc-faq/#missingauthor20"
  | "/series/rfc-faq/#streammanagers"
  | "/series/rfc-faq/#affiliation"
  | "/series/rfc-faq/#iana"
  | "/series/rfc-faq/#whichthat"
  | "/series/rfc-faq/#british"
  | "/series/rfc-tips/"
  | "/series/rfc-tips/#tips-for-reading-rfcs"
  | "/series/rfc-tips/#status"
  | "/series/rfc-tips/#subseries"
  | "/series/rfc-tips/#stream"
  | "/series/rfc-tips/#source"
  | "/series/rfc-tips/#changes-to-rfcs"
  | "/series/rfc-tips/#errata"
  | "/series/rfc-tips/#keywords-for-requirement-levels"
  | "/series/rfc-use/"
  | "/series/rfc-use/#how-can-i-use-rfcs"
  | "/series/rfc/"
  | "/series/rfc/#what-is-an-rfc"
  | "/authors/rfc-edit/"
  | "/authors/rfc-edit/#rfc-editorial-process"
  | "/authors/rfc-how-to/"
  | "/authors/rfc-how-to/#how-to-write-an-rfc"
  | "/authors/rfc-independent-submissions/"
  | "/authors/rfc-independent-submissions/#independent-submissions"
  | "/authors/rfc-independent-submissions/#submission"
  | "/authors/rfc-independent-submissions/#document-reviews"
  | "/authors/rfc-independent-submissions/#iesg-process-review"
  | "/authors/rfc-independent-submissions/#conflict-of-interest-policy"
  | "/authors/rfc-independent-submissions/#independent-submissions-editorial-board"
  | "/authors/rfc-independent-submissions/#an-overview-of-publishing-rfcs-via-the-independent-submissions-process"
  | "/authors/rfc-independent-submissions/#introduction"
  | "/authors/rfc-independent-submissions/#what-sort-of-documents-are-independent-submissions"
  | "/authors/rfc-independent-submissions/#what-are-some-examples-of-rfcs-published-through-the-independent-stream-that-hit-at-least-one-of-those-points"
  | "/authors/rfc-independent-submissions/#what-other-criteria-are-there-for-independent-stream-rfcs"
  | "/authors/rfc-independent-submissions/#what-if-a-document-isnt-appropriate-as-an-independent-submission"
  | "/authors/rfc-independent-submissions/#what-about-intellectual-property-rights-ipr"
  | "/authors/rfc-independent-submissions/#whats-the-process"
  | "/authors/rfc-independent-submissions/#at-what-stage-is-a-document"
  | "/authors/rfc-independent-submissions/#who-makes-decisions-about-independent-submissions"
  | "/authors/rfc-independent-submissions/#who-reviews-submissions"
  | "/authors/rfc-independent-submissions/#where-can-reviews-be-found"
  | "/authors/rfc-independent-submissions/#what-is-ietf-conflict-review"
  | "/authors/rfc-independent-submissions/#how-is-a-decision-made"
  | "/authors/rfc-independent-submissions/#what-happens-if-a-work-is-declined"
  | "/authors/rfc-independent-submissions/#can-an-independent-submission-be-changed-once-it-is-published-as-an-rfc"
  | "/authors/rfc-independent-submissions/#more-questions"
  | "/authors/rfc-style-guide/"
  | "/authors/rfc-style-guide/#style-guide"
  | "/authors/rfc-style-guide/#updates-to-the-rfc-style-guide"
  | "/authors/rfc-style-guide/#musts"
  | "/authors/rfc-style-guide/#recommended"
  | "/authors/rfc-style-guide/#author-choice"
  | "/authors/rfc-style-guide/#xml-formatting"
  | "/authors/rfc-style-guide/#rfc-headers-and-boilerplate"
  | "/authors/rfc-style-guide/#_1-rfc-title-page-header"
  | "/authors/rfc-style-guide/#_2-constructing-a-status-of-this-memo-section"
  | "/authors/rfc-style-guide/#_21-first-paragraph"
  | "/authors/rfc-style-guide/#_22-second-paragraph"
  | "/authors/rfc-style-guide/#_23-third-paragraph"
  | "/authors/rfc-edit/auth48/"
  | "/authors/rfc-edit/auth48/#authors-final-review-auth48"
  | "/authors/rfc-edit/auth48/#template-of-instructions-for-completing-auth48"
  | "/authors/rfc-edit/auth48/#planning-your-review"
  | "/authors/rfc-edit/auth48/#submitting-changes"
  | "/authors/rfc-edit/auth48/#approving-for-publication"
  | "/authors/rfc-edit/auth48/#files"
  | "/authors/rfc-edit/auth48/#tracking-progress"
  | "/authors/rfc-edit/doc-clusters/"
  | "/authors/rfc-edit/doc-clusters/#document-clusters-in-queue"
  | "/authors/rfc-edit/doc-clusters/#document-clusters-in-the-rfc-editor-queue"
  | "/authors/rfc-edit/pub-queue/"
  | "/authors/rfc-edit/pub-queue/#current-publication-queue"
  | "/authors/rfc-edit/pub-queue/#publication-queue"
  | "/authors/rfc-edit/pub-queue/#definitions-of-queue-states"
  | "/authors/rfc-edit/pub-queue/#definitions-of-flags"
  | "/authors/rfc-edit/pub-queue/#definitions-of-missref-generation-numbers"
  | "/authors/rfc-edit/pub-queue/#publication-flow-chart"

export type MarkdownFileValidInternalLinks_aboutContactMd =
  | "#contact"
  | "#report-a-copyright-infringement"

export type MarkdownFileValidInternalLinks_aboutRfcEditorMd =
  | "#about-the-rfc-editor"
  | "#rswg"
  | "#rsab"
  | "#rsce"
  | "#rpc"
  | "#governing-rfcs"

export type MarkdownFileValidInternalLinks_aboutRpcReportsMd =
  | "#reports"
  | "#service-level-agreement"
  | "#notes"
  | "#other-reports"

export type MarkdownFileValidInternalLinks_seriesRfcDownloadMd =
  | "#download-rfcs"
  | "#feed-of-recently-published-rfcs"
  | "#download-rfcs-using-rsync"
  | "#to-get-the-list-of-modules-available-type-rsync-rsyncrfc-editororg-this-will-return-the-following-results"
  | "#to-create-a-mirror-using-a-module"
  | "#download-rfcs-in-tar-or-zip-files"

export type MarkdownFileValidInternalLinks_seriesRfcErrataMd =
  | "#errata-in-rfcs"
  | "#types-of-errata"
  | "#errata-statuses"
  | "#how-to-report-an-erratum"
  | "#search-for-errata"

export type MarkdownFileValidInternalLinks_seriesRfcFaqMd =
  | "#frequently-asked-questions"
  | "#who"
  | "#wg"
  | "#allstds"
  | "#stdtrack"
  | "#statuschanges"
  | "#errata"
  | "#copyright"
  | "#streamcat"
  | "#streamman"
  | "#notified"
  | "#retrieve"
  | "#controlM"
  | "#hardcopy"
  | "#how"
  | "#in-queue"
  | "#howlong"
  | "#reservednumber"
  | "#expedite"
  | "#typos"
  | "#style"
  | "#refs"
  | "#IDrefs"
  | "#lastlook"
  | "#missingauthor"
  | "#involved"
  | "#enhanced"
  | "#sourcefile"
  | "#notprepped"
  | "#april"
  | "#process"
  | "#xmlfile"
  | "#a404xml"
  | "#whichsource"
  | "#changes"
  | "#pagebreaks"
  | "#approval"
  | "#missingauthor20"
  | "#streammanagers"
  | "#affiliation"
  | "#iana"
  | "#whichthat"
  | "#british"

export type MarkdownFileValidInternalLinks_seriesRfcTipsMd =
  | "#tips-for-reading-rfcs"
  | "#status"
  | "#subseries"
  | "#stream"
  | "#source"
  | "#changes-to-rfcs"
  | "#errata"
  | "#keywords-for-requirement-levels"

export type MarkdownFileValidInternalLinks_seriesRfcUseMd =
  | "#how-can-i-use-rfcs"

export type MarkdownFileValidInternalLinks_seriesRfcMd =
  | "#what-is-an-rfc"

export type MarkdownFileValidInternalLinks_authorsRfcEditMd =
  | "#rfc-editorial-process"

export type MarkdownFileValidInternalLinks_authorsRfcHowToMd =
  | "#how-to-write-an-rfc"

export type MarkdownFileValidInternalLinks_authorsRfcIndependentSubmissionsMd =
  | "#independent-submissions"
  | "#submission"
  | "#document-reviews"
  | "#iesg-process-review"
  | "#conflict-of-interest-policy"
  | "#independent-submissions-editorial-board"
  | "#an-overview-of-publishing-rfcs-via-the-independent-submissions-process"
  | "#introduction"
  | "#what-sort-of-documents-are-independent-submissions"
  | "#what-are-some-examples-of-rfcs-published-through-the-independent-stream-that-hit-at-least-one-of-those-points"
  | "#what-other-criteria-are-there-for-independent-stream-rfcs"
  | "#what-if-a-document-isnt-appropriate-as-an-independent-submission"
  | "#what-about-intellectual-property-rights-ipr"
  | "#whats-the-process"
  | "#at-what-stage-is-a-document"
  | "#who-makes-decisions-about-independent-submissions"
  | "#who-reviews-submissions"
  | "#where-can-reviews-be-found"
  | "#what-is-ietf-conflict-review"
  | "#how-is-a-decision-made"
  | "#what-happens-if-a-work-is-declined"
  | "#can-an-independent-submission-be-changed-once-it-is-published-as-an-rfc"
  | "#more-questions"

export type MarkdownFileValidInternalLinks_authorsRfcStyleGuideMd =
  | "#style-guide"
  | "#updates-to-the-rfc-style-guide"
  | "#musts"
  | "#recommended"
  | "#author-choice"
  | "#xml-formatting"
  | "#rfc-headers-and-boilerplate"
  | "#_1-rfc-title-page-header"
  | "#_2-constructing-a-status-of-this-memo-section"
  | "#_21-first-paragraph"
  | "#_22-second-paragraph"
  | "#_23-third-paragraph"

export type MarkdownFileValidInternalLinks_authorsRfcEditAuth48Md =
  | "#authors-final-review-auth48"
  | "#template-of-instructions-for-completing-auth48"
  | "#planning-your-review"
  | "#submitting-changes"
  | "#approving-for-publication"
  | "#files"
  | "#tracking-progress"

export type MarkdownFileValidInternalLinks_authorsRfcEditDocClustersMd =
  | "#document-clusters-in-queue"
  | "#document-clusters-in-the-rfc-editor-queue"

export type MarkdownFileValidInternalLinks_authorsRfcEditPubQueueMd =
  | "#current-publication-queue"
  | "#publication-queue"
  | "#definitions-of-queue-states"
  | "#definitions-of-flags"
  | "#definitions-of-missref-generation-numbers"
  | "#publication-flow-chart"
