apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
  labels:
    appclass: light
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: red
  template:
    metadata:
      labels:
        app: red
        appclass: light
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: red
          image: "ghcr.io/ietf-tools/red:$APP_IMAGE_TAG"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          envFrom:
            - secretRef:
                name: red-secrets-env
          env:
            # ensures the pod gets recreated on every deploy:
            - name: "DEPLOY_UID"
              value: "$DEPLOY_UID"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 1000
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: red
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: red
