apiVersion: apps/v1
kind: Deployment
metadata:
  name: rfced-www
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rfced-www
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rfced-www
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: rfced-www
          image: "ghcr.io/ietf-tools/rfced-www:$APP_IMAGE_TAG"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          envFrom:
            - secretRef:
                name: red-secrets-env
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 1000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rfced-www
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: rfced-www