name: Extractor Vitest, TypeScript check

on:
  push:
    paths:
      - 'rfc-html-extractor/**'
      - 'client/app/utilities/rfc-validators.ts'
      - 'client/app/utilities/rfc-converter-status.ts'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./rfc-html-extractor"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24.x
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies (client)
        run: npm ci
        working-directory: ./client

      - name: Install dependencies (extractor)
        run: npm ci
        working-directory: ./rfc-html-extractor

      - name: Run all other tests
        run: npm run test
        working-directory: ./rfc-html-extractor
